In [1]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
text = ['london london paris','paris london paris']
count_matrix = cv.fit_transform(text)

print(cv.get_feature_names)
print(count_matrix.toarray())

<bound method CountVectorizer.get_feature_names of CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)>
[[2 1]
 [1 2]]


In [2]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(count_matrix)
print(similarity_scores)

[[1.  0.8]
 [0.8 1. ]]


In [3]:
list(enumerate(similarity_scores[1]))

[(0, 0.7999999999999999), (1, 0.9999999999999999)]

In [4]:
import os
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
path =os.getcwd()
print('cwd is %s '%path)


cwd is /Users/isla/Desktop/code/re-demo 


In [5]:
os.chdir('/Users/isla/Downloads/introduction-to-machine-learning-master/Building a Movie Recommendation Engine')


In [7]:
df = pd.read_csv('movie_dataset.csv')
df.head(2)
df.shape

(4803, 24)

In [12]:
features = ['keywords','cast','genres','director']
def combine_features(row):
    return row['keywords']+' '+row['cast']+' '+row['genres']+' '+row['director']


for feature in features:
    df[feature] = df[feature].fillna('')

df['combined_features'] = df.apply(combine_features,axis=1)
df.head(2)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ...  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average vote_count  \
0                                    Avatar           7.2      11800   
1  Pirates of the Caribbean: At World's End           6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski   

                                   combined_features  
0  culture clash future space war space colony so...  
1  ocean drug abuse exotic island east india trad...  

[2 rows x 25 columns]

In [32]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
cosine_sim = cosine_similarity(count_matrix)

def get_title_from_index(index):
    return df[df.index==index]['title'].values[0]


def get_index_from_title(title):
    return df[df.title == title]['index'].values[0]

movie_user_likes = 'Avatar'
movie_index = get_index_from_title('Avatar')
similar_movies = list(enumerate(cosine_sim[movie_index]))

sorted_similar_movies = sorted(similar_movies,key = lambda x:x[1], reverse=True)[1:]

i = 0
print('top5 similar movies to '+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i +=1
    if i>=5:
        break

top5 similar movies to Avatar are:

Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond


In [37]:
print(cosine_sim)

[[1.         0.10540926 0.12038585 ... 0.         0.         0.        ]
 [0.10540926 1.         0.0761387  ... 0.03651484 0.         0.        ]
 [0.12038585 0.0761387  1.         ... 0.         0.11145564 0.        ]
 ...
 [0.         0.03651484 0.         ... 1.         0.         0.04264014]
 [0.         0.         0.11145564 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.04264014 0.         1.        ]]
